name: Alternative test

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  contents: read

jobs:
  debug-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
          arch: x64
      - uses: julia-actions/cache@v2
      - name: Debug test
        run: |
          touch Project.toml
          julia --project -O3 -e 'import Pkg; Pkg.add(["MPI", "MPIPreferences"]); using MPIPreferences; MPIPreferences.use_jll_binary("OpenMPI_jll")'
          julia --project -O3 -e 'using MPI; MPI.install_mpiexecjl(; destdir=".")'
          julia --project -O3 -e 'import Pkg; Pkg.add(["HDF5", "NCDatasets"])'
          julia --project -O3 -e 'import Pkg; Pkg.precompile()'
        shell: bash
