# Based on example from https://github.com/julia-actions/julia-runtest
name: Debug with default check-bounds

on: [push, pull_request, workflow_dispatch]

jobs:
  debug-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
          arch: x64
      - name: Debug test
        run: |
          touch Project.toml
          julia --project -O3 -e 'using Pkg; Pkg.add(["MPI", "MPIPreferences"]); using MPIPreferences; MPIPreferences.use_jll_binary("OpenMPI_jll")'
          #julia --project -O3 -e 'using Pkg; Pkg.add(name="HDF5_jll", version="v1.14.3")'
          julia --project -O3 -e 'using Pkg; Pkg.add("HDF5"); Pkg.precompile()'
