name: HDF5_jll@1.14.2

on: [push, pull_request, workflow_dispatch]

jobs:
  debug-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
          arch: x64
      - name: Debug test
        run: |
          touch Project.toml
          julia --project -O3 -e 'import Pkg; Pkg.add(["MPI", "MPIPreferences"]); using MPIPreferences; MPIPreferences.use_jll_binary("OpenMPI_jll")'
          julia --project -O3 -e 'import Pkg; Pkg.add(name="HDF5_jll", version="1.14.2"); Pkg.add(["HDF5"]); Pkg.precompile()'
